# Generated by Django 5.1 on 2024-08-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signinmodel',
            name='cpas',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='signinmodel',
            name='pas',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='signinmodel',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
