# Generated by Django 5.1 on 2024-08-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_alter_course_c_hostal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='c_hostal',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=50),
        ),
    ]
