# Generated by Django 5.1.1 on 2024-11-04 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_studentlogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlogin',
            name='s_address',
        ),
        migrations.RemoveField(
            model_name='studentlogin',
            name='s_branch',
        ),
        migrations.RemoveField(
            model_name='studentlogin',
            name='s_course',
        ),
        migrations.RemoveField(
            model_name='studentlogin',
            name='s_name',
        ),
        migrations.RemoveField(
            model_name='studentlogin',
            name='s_year',
        ),
    ]
