# Generated by Django 5.1.1 on 2024-11-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_studentinformation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentInformation',
        ),
    ]
