# Generated by Django 5.1.1 on 2024-11-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0009_delete_studentinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_id', models.CharField(max_length=15)),
                ('fac_name', models.CharField(max_length=100)),
                ('fac_dep', models.CharField(max_length=100)),
                ('fac_sub', models.CharField(max_length=100)),
                ('fac_profile', models.ImageField(upload_to='')),
                ('fac_exp', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
