# Generated by Django 5.1.1 on 2024-11-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0010_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='fac_exp',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='fac_profile',
            field=models.ImageField(upload_to='media'),
        ),
    ]
