# Generated by Django 5.1.1 on 2024-11-07 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0013_alter_faculty_fac_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('photo', models.ImageField(upload_to='media/')),
                ('mobile', models.IntegerField(unique=True)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.course')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.signinmodel')),
            ],
        ),
    ]
